/* soapH.h
   Generated by gSOAP 2.8.1 from ns_ProbeOp.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

/* _wsa__ReplyAfter is a typedef element/attribute synonym for unsignedInt */

#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
#endif

#define soap_default__wsa__ReplyAfter(soap, a) soap_default_unsignedInt(soap, a)


#define soap_out__wsa__ReplyAfter soap_out_unsignedInt


#define soap_in__wsa__ReplyAfter soap_in_unsignedInt


#ifndef soap_write__wsa__ReplyAfter
#define soap_write__wsa__ReplyAfter(soap, data) ( soap_begin_send(soap) || soap_put__wsa__ReplyAfter(soap, data, "wsa:ReplyAfter", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__ReplyAfter soap_put_unsignedInt


#ifndef soap_read__wsa__ReplyAfter
#define soap_read__wsa__ReplyAfter(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__ReplyAfter(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__ReplyAfter soap_get_unsignedInt


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__FaultSubcodeValues(struct soap*, enum wsa__FaultSubcodeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__FaultSubcodeValues(struct soap*, const char*, int, const enum wsa__FaultSubcodeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_wsa__FaultSubcodeValues2s(struct soap*, enum wsa__FaultSubcodeValues);
SOAP_FMAC3 enum wsa__FaultSubcodeValues * SOAP_FMAC4 soap_in_wsa__FaultSubcodeValues(struct soap*, const char*, enum wsa__FaultSubcodeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2wsa__FaultSubcodeValues(struct soap*, const char*, enum wsa__FaultSubcodeValues *);

#ifndef soap_write_wsa__FaultSubcodeValues
#define soap_write_wsa__FaultSubcodeValues(soap, data) ( soap_begin_send(soap) || soap_put_wsa__FaultSubcodeValues(soap, data, "wsa:FaultSubcodeValues", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__FaultSubcodeValues(struct soap*, const enum wsa__FaultSubcodeValues *, const char*, const char*);

#ifndef soap_read_wsa__FaultSubcodeValues
#define soap_read_wsa__FaultSubcodeValues(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__FaultSubcodeValues(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum wsa__FaultSubcodeValues * SOAP_FMAC4 soap_get_wsa__FaultSubcodeValues(struct soap*, enum wsa__FaultSubcodeValues *, const char*, const char*);

#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__RelationshipTypeValues(struct soap*, enum wsa__RelationshipTypeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__RelationshipTypeValues(struct soap*, const char*, int, const enum wsa__RelationshipTypeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_wsa__RelationshipTypeValues2s(struct soap*, enum wsa__RelationshipTypeValues);
SOAP_FMAC3 enum wsa__RelationshipTypeValues * SOAP_FMAC4 soap_in_wsa__RelationshipTypeValues(struct soap*, const char*, enum wsa__RelationshipTypeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2wsa__RelationshipTypeValues(struct soap*, const char*, enum wsa__RelationshipTypeValues *);

#ifndef soap_write_wsa__RelationshipTypeValues
#define soap_write_wsa__RelationshipTypeValues(soap, data) ( soap_begin_send(soap) || soap_put_wsa__RelationshipTypeValues(soap, data, "wsa:RelationshipTypeValues", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__RelationshipTypeValues(struct soap*, const enum wsa__RelationshipTypeValues *, const char*, const char*);

#ifndef soap_read_wsa__RelationshipTypeValues
#define soap_read_wsa__RelationshipTypeValues(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__RelationshipTypeValues(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 enum wsa__RelationshipTypeValues * SOAP_FMAC4 soap_get_wsa__RelationshipTypeValues(struct soap*, enum wsa__RelationshipTypeValues *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_d__ProbeMatches
#define SOAP_TYPE_d__ProbeMatches (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ProbeMatches(struct soap*, struct d__ProbeMatches *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ProbeMatches(struct soap*, const struct d__ProbeMatches *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ProbeMatches(struct soap*, const char*, int, const struct d__ProbeMatches *, const char*);
SOAP_FMAC3 struct d__ProbeMatches * SOAP_FMAC4 soap_in_d__ProbeMatches(struct soap*, const char*, struct d__ProbeMatches *, const char*);

#ifndef soap_write_d__ProbeMatches
#define soap_write_d__ProbeMatches(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ProbeMatches(soap, data), 0) || soap_put_d__ProbeMatches(soap, data, "d:ProbeMatches", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ProbeMatches(struct soap*, const struct d__ProbeMatches *, const char*, const char*);

#ifndef soap_read_d__ProbeMatches
#define soap_read_d__ProbeMatches(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ProbeMatches(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatches * SOAP_FMAC4 soap_get_d__ProbeMatches(struct soap*, struct d__ProbeMatches *, const char*, const char*);

#define soap_new_d__ProbeMatches(soap, n) soap_instantiate_d__ProbeMatches(soap, n, NULL, NULL, NULL)


#define soap_delete_d__ProbeMatches(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct d__ProbeMatches * SOAP_FMAC2 soap_instantiate_d__ProbeMatches(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_d__ProbeMatches(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_d__Probe
#define SOAP_TYPE_d__Probe (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__Probe(struct soap*, struct d__Probe *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__Probe(struct soap*, const struct d__Probe *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__Probe(struct soap*, const char*, int, const struct d__Probe *, const char*);
SOAP_FMAC3 struct d__Probe * SOAP_FMAC4 soap_in_d__Probe(struct soap*, const char*, struct d__Probe *, const char*);

#ifndef soap_write_d__Probe
#define soap_write_d__Probe(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__Probe(soap, data), 0) || soap_put_d__Probe(soap, data, "d:Probe", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__Probe(struct soap*, const struct d__Probe *, const char*, const char*);

#ifndef soap_read_d__Probe
#define soap_read_d__Probe(soap, data) ( soap_begin_recv(soap) || !soap_get_d__Probe(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__Probe * SOAP_FMAC4 soap_get_d__Probe(struct soap*, struct d__Probe *, const char*, const char*);

#define soap_new_d__Probe(soap, n) soap_instantiate_d__Probe(soap, n, NULL, NULL, NULL)


#define soap_delete_d__Probe(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct d__Probe * SOAP_FMAC2 soap_instantiate_d__Probe(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_d__Probe(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_d__ProbeMatchType
#define SOAP_TYPE_d__ProbeMatchType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__ProbeMatchType(struct soap*, struct d__ProbeMatchType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__ProbeMatchType(struct soap*, const struct d__ProbeMatchType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__ProbeMatchType(struct soap*, const char*, int, const struct d__ProbeMatchType *, const char*);
SOAP_FMAC3 struct d__ProbeMatchType * SOAP_FMAC4 soap_in_d__ProbeMatchType(struct soap*, const char*, struct d__ProbeMatchType *, const char*);

#ifndef soap_write_d__ProbeMatchType
#define soap_write_d__ProbeMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__ProbeMatchType(soap, data), 0) || soap_put_d__ProbeMatchType(soap, data, "d:ProbeMatchType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__ProbeMatchType(struct soap*, const struct d__ProbeMatchType *, const char*, const char*);

#ifndef soap_read_d__ProbeMatchType
#define soap_read_d__ProbeMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__ProbeMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchType * SOAP_FMAC4 soap_get_d__ProbeMatchType(struct soap*, struct d__ProbeMatchType *, const char*, const char*);

#define soap_new_d__ProbeMatchType(soap, n) soap_instantiate_d__ProbeMatchType(soap, n, NULL, NULL, NULL)


#define soap_delete_d__ProbeMatchType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct d__ProbeMatchType * SOAP_FMAC2 soap_instantiate_d__ProbeMatchType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_d__ProbeMatchType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_d__EndpointReferenceType
#define SOAP_TYPE_d__EndpointReferenceType (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_d__EndpointReferenceType(struct soap*, struct d__EndpointReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_d__EndpointReferenceType(struct soap*, const struct d__EndpointReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_d__EndpointReferenceType(struct soap*, const char*, int, const struct d__EndpointReferenceType *, const char*);
SOAP_FMAC3 struct d__EndpointReferenceType * SOAP_FMAC4 soap_in_d__EndpointReferenceType(struct soap*, const char*, struct d__EndpointReferenceType *, const char*);

#ifndef soap_write_d__EndpointReferenceType
#define soap_write_d__EndpointReferenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_d__EndpointReferenceType(soap, data), 0) || soap_put_d__EndpointReferenceType(soap, data, "d:EndpointReferenceType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_d__EndpointReferenceType(struct soap*, const struct d__EndpointReferenceType *, const char*, const char*);

#ifndef soap_read_d__EndpointReferenceType
#define soap_read_d__EndpointReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_d__EndpointReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__EndpointReferenceType * SOAP_FMAC4 soap_get_d__EndpointReferenceType(struct soap*, struct d__EndpointReferenceType *, const char*, const char*);

#define soap_new_d__EndpointReferenceType(soap, n) soap_instantiate_d__EndpointReferenceType(soap, n, NULL, NULL, NULL)


#define soap_delete_d__EndpointReferenceType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct d__EndpointReferenceType * SOAP_FMAC2 soap_instantiate_d__EndpointReferenceType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_d__EndpointReferenceType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* _wsa__FaultTo is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
#endif

#define soap_default__wsa__FaultTo(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__FaultTo(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__FaultTo soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__FaultTo soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__FaultTo
#define soap_write__wsa__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__FaultTo(soap, data), 0) || soap_put__wsa__FaultTo(soap, data, "wsa:FaultTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__FaultTo soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__FaultTo
#define soap_read__wsa__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__FaultTo soap_get_wsa__EndpointReferenceType


#define soap_new__wsa__FaultTo(soap, n) soap_instantiate__wsa__FaultTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa__FaultTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa__FaultTo soap_instantiate_wsa__EndpointReferenceType


#define soap_copy__wsa__FaultTo soap_copy_wsa__EndpointReferenceType

/* _wsa__ReplyTo is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
#endif

#define soap_default__wsa__ReplyTo(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__ReplyTo(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__ReplyTo soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__ReplyTo soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__ReplyTo
#define soap_write__wsa__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__ReplyTo(soap, data), 0) || soap_put__wsa__ReplyTo(soap, data, "wsa:ReplyTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__ReplyTo soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__ReplyTo
#define soap_read__wsa__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__ReplyTo soap_get_wsa__EndpointReferenceType


#define soap_new__wsa__ReplyTo(soap, n) soap_instantiate__wsa__ReplyTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa__ReplyTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa__ReplyTo soap_instantiate_wsa__EndpointReferenceType


#define soap_copy__wsa__ReplyTo soap_copy_wsa__EndpointReferenceType

/* _wsa__From is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
#endif

#define soap_default__wsa__From(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__From(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__From soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__From soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__From
#define soap_write__wsa__From(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__From(soap, data), 0) || soap_put__wsa__From(soap, data, "wsa:From", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__From soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__From
#define soap_read__wsa__From(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__From soap_get_wsa__EndpointReferenceType


#define soap_new__wsa__From(soap, n) soap_instantiate__wsa__From(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa__From(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa__From soap_instantiate_wsa__EndpointReferenceType


#define soap_copy__wsa__From soap_copy_wsa__EndpointReferenceType

/* _wsa__RelatesTo is a typedef element/attribute synonym for wsa__Relationship */

#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
#endif

#define soap_default__wsa__RelatesTo(soap, a) soap_default_wsa__Relationship(soap, a)


#define soap_serialize__wsa__RelatesTo(soap, a) soap_serialize_wsa__Relationship(soap, a)


#define soap_out__wsa__RelatesTo soap_out_wsa__Relationship


#define soap_in__wsa__RelatesTo soap_in_wsa__Relationship


#ifndef soap_write__wsa__RelatesTo
#define soap_write__wsa__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__RelatesTo(soap, data), 0) || soap_put__wsa__RelatesTo(soap, data, "wsa:RelatesTo", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__RelatesTo soap_put_wsa__Relationship


#ifndef soap_read__wsa__RelatesTo
#define soap_read__wsa__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__RelatesTo soap_get_wsa__Relationship


#define soap_new__wsa__RelatesTo(soap, n) soap_instantiate__wsa__RelatesTo(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa__RelatesTo(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa__RelatesTo soap_instantiate_wsa__Relationship


#define soap_copy__wsa__RelatesTo soap_copy_wsa__Relationship

/* _wsa__EndpointReference is a typedef element/attribute synonym for wsa__EndpointReferenceType */

#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
#endif

#define soap_default__wsa__EndpointReference(soap, a) soap_default_wsa__EndpointReferenceType(soap, a)


#define soap_serialize__wsa__EndpointReference(soap, a) soap_serialize_wsa__EndpointReferenceType(soap, a)


#define soap_out__wsa__EndpointReference soap_out_wsa__EndpointReferenceType


#define soap_in__wsa__EndpointReference soap_in_wsa__EndpointReferenceType


#ifndef soap_write__wsa__EndpointReference
#define soap_write__wsa__EndpointReference(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__EndpointReference(soap, data), 0) || soap_put__wsa__EndpointReference(soap, data, "wsa:EndpointReference", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__EndpointReference soap_put_wsa__EndpointReferenceType


#ifndef soap_read__wsa__EndpointReference
#define soap_read__wsa__EndpointReference(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__EndpointReference(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__EndpointReference soap_get_wsa__EndpointReferenceType


#define soap_new__wsa__EndpointReference(soap, n) soap_instantiate__wsa__EndpointReference(soap, n, NULL, NULL, NULL)


#define soap_delete__wsa__EndpointReference(soap, p) soap_delete(soap, p)


#define soap_instantiate__wsa__EndpointReference soap_instantiate_wsa__EndpointReferenceType


#define soap_copy__wsa__EndpointReference soap_copy_wsa__EndpointReferenceType

#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__Relationship(struct soap*, struct wsa__Relationship *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__Relationship(struct soap*, const struct wsa__Relationship *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__Relationship(struct soap*, const char*, int, const struct wsa__Relationship *, const char*);
SOAP_FMAC3 struct wsa__Relationship * SOAP_FMAC4 soap_in_wsa__Relationship(struct soap*, const char*, struct wsa__Relationship *, const char*);

#ifndef soap_write_wsa__Relationship
#define soap_write_wsa__Relationship(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__Relationship(soap, data), 0) || soap_put_wsa__Relationship(soap, data, "wsa:Relationship", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__Relationship(struct soap*, const struct wsa__Relationship *, const char*, const char*);

#ifndef soap_read_wsa__Relationship
#define soap_read_wsa__Relationship(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__Relationship(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__Relationship * SOAP_FMAC4 soap_get_wsa__Relationship(struct soap*, struct wsa__Relationship *, const char*, const char*);

#define soap_new_wsa__Relationship(soap, n) soap_instantiate_wsa__Relationship(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa__Relationship(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa__Relationship * SOAP_FMAC2 soap_instantiate_wsa__Relationship(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa__Relationship(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ServiceNameType(struct soap*, const struct wsa__ServiceNameType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ServiceNameType(struct soap*, const char*, int, const struct wsa__ServiceNameType *, const char*);
SOAP_FMAC3 struct wsa__ServiceNameType * SOAP_FMAC4 soap_in_wsa__ServiceNameType(struct soap*, const char*, struct wsa__ServiceNameType *, const char*);

#ifndef soap_write_wsa__ServiceNameType
#define soap_write_wsa__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ServiceNameType(soap, data), 0) || soap_put_wsa__ServiceNameType(soap, data, "wsa:ServiceNameType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ServiceNameType(struct soap*, const struct wsa__ServiceNameType *, const char*, const char*);

#ifndef soap_read_wsa__ServiceNameType
#define soap_read_wsa__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ServiceNameType * SOAP_FMAC4 soap_get_wsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *, const char*, const char*);

#define soap_new_wsa__ServiceNameType(soap, n) soap_instantiate_wsa__ServiceNameType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa__ServiceNameType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa__ServiceNameType * SOAP_FMAC2 soap_instantiate_wsa__ServiceNameType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa__ServiceNameType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ReferenceParametersType(struct soap*, const struct wsa__ReferenceParametersType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ReferenceParametersType(struct soap*, const char*, int, const struct wsa__ReferenceParametersType *, const char*);
SOAP_FMAC3 struct wsa__ReferenceParametersType * SOAP_FMAC4 soap_in_wsa__ReferenceParametersType(struct soap*, const char*, struct wsa__ReferenceParametersType *, const char*);

#ifndef soap_write_wsa__ReferenceParametersType
#define soap_write_wsa__ReferenceParametersType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ReferenceParametersType(soap, data), 0) || soap_put_wsa__ReferenceParametersType(soap, data, "wsa:ReferenceParametersType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ReferenceParametersType(struct soap*, const struct wsa__ReferenceParametersType *, const char*, const char*);

#ifndef soap_read_wsa__ReferenceParametersType
#define soap_read_wsa__ReferenceParametersType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ReferenceParametersType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferenceParametersType * SOAP_FMAC4 soap_get_wsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *, const char*, const char*);

#define soap_new_wsa__ReferenceParametersType(soap, n) soap_instantiate_wsa__ReferenceParametersType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa__ReferenceParametersType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa__ReferenceParametersType * SOAP_FMAC2 soap_instantiate_wsa__ReferenceParametersType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa__ReferenceParametersType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__ReferencePropertiesType(struct soap*, const struct wsa__ReferencePropertiesType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__ReferencePropertiesType(struct soap*, const char*, int, const struct wsa__ReferencePropertiesType *, const char*);
SOAP_FMAC3 struct wsa__ReferencePropertiesType * SOAP_FMAC4 soap_in_wsa__ReferencePropertiesType(struct soap*, const char*, struct wsa__ReferencePropertiesType *, const char*);

#ifndef soap_write_wsa__ReferencePropertiesType
#define soap_write_wsa__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__ReferencePropertiesType(soap, data), 0) || soap_put_wsa__ReferencePropertiesType(soap, data, "wsa:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__ReferencePropertiesType(struct soap*, const struct wsa__ReferencePropertiesType *, const char*, const char*);

#ifndef soap_read_wsa__ReferencePropertiesType
#define soap_read_wsa__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferencePropertiesType * SOAP_FMAC4 soap_get_wsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *, const char*, const char*);

#define soap_new_wsa__ReferencePropertiesType(soap, n) soap_instantiate_wsa__ReferencePropertiesType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa__ReferencePropertiesType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa__ReferencePropertiesType * SOAP_FMAC2 soap_instantiate_wsa__ReferencePropertiesType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa__ReferencePropertiesType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_wsa__EndpointReferenceType(struct soap*, struct wsa__EndpointReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_wsa__EndpointReferenceType(struct soap*, const struct wsa__EndpointReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_wsa__EndpointReferenceType(struct soap*, const char*, int, const struct wsa__EndpointReferenceType *, const char*);
SOAP_FMAC3 struct wsa__EndpointReferenceType * SOAP_FMAC4 soap_in_wsa__EndpointReferenceType(struct soap*, const char*, struct wsa__EndpointReferenceType *, const char*);

#ifndef soap_write_wsa__EndpointReferenceType
#define soap_write_wsa__EndpointReferenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_wsa__EndpointReferenceType(soap, data), 0) || soap_put_wsa__EndpointReferenceType(soap, data, "wsa:EndpointReferenceType", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_wsa__EndpointReferenceType(struct soap*, const struct wsa__EndpointReferenceType *, const char*, const char*);

#ifndef soap_read_wsa__EndpointReferenceType
#define soap_read_wsa__EndpointReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_wsa__EndpointReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType * SOAP_FMAC4 soap_get_wsa__EndpointReferenceType(struct soap*, struct wsa__EndpointReferenceType *, const char*, const char*);

#define soap_new_wsa__EndpointReferenceType(soap, n) soap_instantiate_wsa__EndpointReferenceType(soap, n, NULL, NULL, NULL)


#define soap_delete_wsa__EndpointReferenceType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct wsa__EndpointReferenceType * SOAP_FMAC2 soap_instantiate_wsa__EndpointReferenceType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_wsa__EndpointReferenceType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTod__ProbeMatchType
#define SOAP_TYPE_PointerTod__ProbeMatchType (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__ProbeMatchType(struct soap*, const char *, int, struct d__ProbeMatchType *const*, const char *);
SOAP_FMAC3 struct d__ProbeMatchType ** SOAP_FMAC4 soap_in_PointerTod__ProbeMatchType(struct soap*, const char*, struct d__ProbeMatchType **, const char*);

#ifndef soap_write_PointerTod__ProbeMatchType
#define soap_write_PointerTod__ProbeMatchType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__ProbeMatchType(soap, data), 0) || soap_put_PointerTod__ProbeMatchType(soap, data, "d:ProbeMatchType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__ProbeMatchType
#define soap_read_PointerTod__ProbeMatchType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__ProbeMatchType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__ProbeMatchType ** SOAP_FMAC4 soap_get_PointerTod__ProbeMatchType(struct soap*, struct d__ProbeMatchType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTod__EndpointReferenceType
#define SOAP_TYPE_PointerTod__EndpointReferenceType (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTod__EndpointReferenceType(struct soap*, struct d__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTod__EndpointReferenceType(struct soap*, const char *, int, struct d__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct d__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTod__EndpointReferenceType(struct soap*, const char*, struct d__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTod__EndpointReferenceType
#define soap_write_PointerTod__EndpointReferenceType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTod__EndpointReferenceType(soap, data), 0) || soap_put_PointerTod__EndpointReferenceType(soap, data, "d:EndpointReferenceType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTod__EndpointReferenceType(struct soap*, struct d__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTod__EndpointReferenceType
#define soap_read_PointerTod__EndpointReferenceType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTod__EndpointReferenceType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct d__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTod__EndpointReferenceType(struct soap*, struct d__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__FaultTo
#define SOAP_TYPE_PointerTo_wsa__FaultTo (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__FaultTo(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__FaultTo(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__FaultTo
#define soap_write_PointerTo_wsa__FaultTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__FaultTo(soap, data), 0) || soap_put_PointerTo_wsa__FaultTo(soap, data, "wsa:FaultTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__FaultTo
#define soap_read_PointerTo_wsa__FaultTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__FaultTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__FaultTo(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__ReplyTo
#define SOAP_TYPE_PointerTo_wsa__ReplyTo (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__ReplyTo(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__ReplyTo(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__ReplyTo
#define soap_write_PointerTo_wsa__ReplyTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__ReplyTo(soap, data), 0) || soap_put_PointerTo_wsa__ReplyTo(soap, data, "wsa:ReplyTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__ReplyTo
#define soap_read_PointerTo_wsa__ReplyTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__ReplyTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__ReplyTo(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__From
#define SOAP_TYPE_PointerTo_wsa__From (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__From(struct soap*, const char *, int, struct wsa__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerTo_wsa__From(struct soap*, const char*, struct wsa__EndpointReferenceType **, const char*);

#ifndef soap_write_PointerTo_wsa__From
#define soap_write_PointerTo_wsa__From(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__From(soap, data), 0) || soap_put_PointerTo_wsa__From(soap, data, "wsa:From", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__From
#define soap_read_PointerTo_wsa__From(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__From(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerTo_wsa__From(struct soap*, struct wsa__EndpointReferenceType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_wsa__RelatesTo
#define SOAP_TYPE_PointerTo_wsa__RelatesTo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_wsa__RelatesTo(struct soap*, const char *, int, struct wsa__Relationship *const*, const char *);
SOAP_FMAC3 struct wsa__Relationship ** SOAP_FMAC4 soap_in_PointerTo_wsa__RelatesTo(struct soap*, const char*, struct wsa__Relationship **, const char*);

#ifndef soap_write_PointerTo_wsa__RelatesTo
#define soap_write_PointerTo_wsa__RelatesTo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_wsa__RelatesTo(soap, data), 0) || soap_put_PointerTo_wsa__RelatesTo(soap, data, "wsa:RelatesTo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship *const*, const char*, const char*);

#ifndef soap_read_PointerTo_wsa__RelatesTo
#define soap_read_PointerTo_wsa__RelatesTo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_wsa__RelatesTo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__Relationship ** SOAP_FMAC4 soap_get_PointerTo_wsa__RelatesTo(struct soap*, struct wsa__Relationship **, const char*, const char*);

/* _wsa__Action is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
#endif

#define soap_default__wsa__Action(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__Action(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__Action soap_out_string


#define soap_in__wsa__Action soap_in_string


#ifndef soap_write__wsa__Action
#define soap_write__wsa__Action(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__Action(soap, data), 0) || soap_put__wsa__Action(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__Action soap_put_string


#ifndef soap_read__wsa__Action
#define soap_read__wsa__Action(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__Action(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__Action soap_get_string


/* _wsa__To is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
#endif

#define soap_default__wsa__To(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__To(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__To soap_out_string


#define soap_in__wsa__To soap_in_string


#ifndef soap_write__wsa__To
#define soap_write__wsa__To(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__To(soap, data), 0) || soap_put__wsa__To(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__To soap_put_string


#ifndef soap_read__wsa__To
#define soap_read__wsa__To(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__To(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__To soap_get_string


/* _wsa__MessageID is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
#endif

#define soap_default__wsa__MessageID(soap, a) soap_default_string(soap, a)


#define soap_serialize__wsa__MessageID(soap, a) soap_serialize_string(soap, a)


#define soap_out__wsa__MessageID soap_out_string


#define soap_in__wsa__MessageID soap_in_string


#ifndef soap_write__wsa__MessageID
#define soap_write__wsa__MessageID(soap, data) ( soap_begin_send(soap) || (soap_serialize__wsa__MessageID(soap, data), 0) || soap_put__wsa__MessageID(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__wsa__MessageID soap_put_string


#ifndef soap_read__wsa__MessageID
#define soap_read__wsa__MessageID(soap, data) ( soap_begin_recv(soap) || !soap_get__wsa__MessageID(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__wsa__MessageID soap_get_string


#ifndef SOAP_TYPE_PointerTowsa__ServiceNameType
#define SOAP_TYPE_PointerTowsa__ServiceNameType (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ServiceNameType(struct soap*, const char *, int, struct wsa__ServiceNameType *const*, const char *);
SOAP_FMAC3 struct wsa__ServiceNameType ** SOAP_FMAC4 soap_in_PointerTowsa__ServiceNameType(struct soap*, const char*, struct wsa__ServiceNameType **, const char*);

#ifndef soap_write_PointerTowsa__ServiceNameType
#define soap_write_PointerTowsa__ServiceNameType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ServiceNameType(soap, data), 0) || soap_put_PointerTowsa__ServiceNameType(soap, data, "wsa:ServiceNameType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ServiceNameType
#define soap_read_PointerTowsa__ServiceNameType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ServiceNameType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ServiceNameType ** SOAP_FMAC4 soap_get_PointerTowsa__ServiceNameType(struct soap*, struct wsa__ServiceNameType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_QName
#define SOAP_TYPE_PointerTo_QName (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_QName(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_QName(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTo_QName(struct soap*, const char*, char ***, const char*);

#ifndef soap_write_PointerTo_QName
#define soap_write_PointerTo_QName(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_QName(soap, data), 0) || soap_put_PointerTo_QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_QName(struct soap*, char **const*, const char*, const char*);

#ifndef soap_read_PointerTo_QName
#define soap_read_PointerTo_QName(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTo_QName(struct soap*, char ***, const char*, const char*);

#ifndef SOAP_TYPE_PointerTowsa__ReferenceParametersType
#define SOAP_TYPE_PointerTowsa__ReferenceParametersType (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ReferenceParametersType(struct soap*, const char *, int, struct wsa__ReferenceParametersType *const*, const char *);
SOAP_FMAC3 struct wsa__ReferenceParametersType ** SOAP_FMAC4 soap_in_PointerTowsa__ReferenceParametersType(struct soap*, const char*, struct wsa__ReferenceParametersType **, const char*);

#ifndef soap_write_PointerTowsa__ReferenceParametersType
#define soap_write_PointerTowsa__ReferenceParametersType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ReferenceParametersType(soap, data), 0) || soap_put_PointerTowsa__ReferenceParametersType(soap, data, "wsa:ReferenceParametersType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ReferenceParametersType
#define soap_read_PointerTowsa__ReferenceParametersType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ReferenceParametersType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferenceParametersType ** SOAP_FMAC4 soap_get_PointerTowsa__ReferenceParametersType(struct soap*, struct wsa__ReferenceParametersType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTowsa__ReferencePropertiesType
#define SOAP_TYPE_PointerTowsa__ReferencePropertiesType (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTowsa__ReferencePropertiesType(struct soap*, const char *, int, struct wsa__ReferencePropertiesType *const*, const char *);
SOAP_FMAC3 struct wsa__ReferencePropertiesType ** SOAP_FMAC4 soap_in_PointerTowsa__ReferencePropertiesType(struct soap*, const char*, struct wsa__ReferencePropertiesType **, const char*);

#ifndef soap_write_PointerTowsa__ReferencePropertiesType
#define soap_write_PointerTowsa__ReferencePropertiesType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTowsa__ReferencePropertiesType(soap, data), 0) || soap_put_PointerTowsa__ReferencePropertiesType(soap, data, "wsa:ReferencePropertiesType", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType *const*, const char*, const char*);

#ifndef soap_read_PointerTowsa__ReferencePropertiesType
#define soap_read_PointerTowsa__ReferencePropertiesType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTowsa__ReferencePropertiesType(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct wsa__ReferencePropertiesType ** SOAP_FMAC4 soap_get_PointerTowsa__ReferencePropertiesType(struct soap*, struct wsa__ReferencePropertiesType **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
